package jogodamemoria;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class Tela extends javax.swing.JFrame {

    int rodada = 0;
    int player;
    int pontuacao;
    int dificuldade = 250;
    List<JButton> sequencia = new ArrayList<>();
    List<JButton> sequenciaPlayer = new ArrayList<>();
    List<JButton> botao = new ArrayList<>();
    List<Object> pontos = new ArrayList<>();
    boolean clique = false;
    DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bto2 = new javax.swing.JButton();
        bto3 = new javax.swing.JButton();
        bto1 = new javax.swing.JButton();
        bto5 = new javax.swing.JButton();
        bto4 = new javax.swing.JButton();
        bto6 = new javax.swing.JButton();
        bto9 = new javax.swing.JButton();
        bto8 = new javax.swing.JButton();
        bto7 = new javax.swing.JButton();
        btoIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bto2.setEnabled(false);
        bto2.setPreferredSize(new java.awt.Dimension(50, 50));
        bto2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bto2MousePressed(evt);
            }
        });

        bto3.setEnabled(false);
        bto3.setPreferredSize(new java.awt.Dimension(50, 50));
        bto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bto3MouseClicked(evt);
            }
        });

        bto1.setEnabled(false);
        bto1.setPreferredSize(new java.awt.Dimension(50, 50));
        bto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bto1MouseClicked(evt);
            }
        });

        bto5.setEnabled(false);
        bto5.setPreferredSize(new java.awt.Dimension(50, 50));
        bto5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bto5MouseClicked(evt);
            }
        });

        bto4.setEnabled(false);
        bto4.setPreferredSize(new java.awt.Dimension(50, 50));
        bto4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bto4MouseClicked(evt);
            }
        });

        bto6.setEnabled(false);
        bto6.setPreferredSize(new java.awt.Dimension(50, 50));
        bto6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bto6MouseClicked(evt);
            }
        });

        bto9.setEnabled(false);
        bto9.setPreferredSize(new java.awt.Dimension(50, 50));
        bto9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bto9MouseClicked(evt);
            }
        });

        bto8.setEnabled(false);
        bto8.setPreferredSize(new java.awt.Dimension(50, 50));
        bto8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bto8MouseClicked(evt);
            }
        });

        bto7.setEnabled(false);
        bto7.setPreferredSize(new java.awt.Dimension(50, 50));
        bto7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bto7MouseClicked(evt);
            }
        });

        btoIniciar.setBackground(new java.awt.Color(153, 255, 0));
        btoIniciar.setText("Iniciar");
        btoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btoIniciarActionPerformed(evt);
            }
        });

        jLabel1.setText("RODADA:");

        jLabel2.setText("PONTUAÇÃO: ");

        jLabel3.setText("DIFICULDADE");

        jLabel4.setText("Nome do Jogo - Nome do Aluno - RA");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Médio", "Díficil" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jList1);

        jTextField1.setText("Nome do Jogador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btoIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bto4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bto5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bto6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bto1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bto2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bto3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bto7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bto8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bto9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(btoIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bto2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bto3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bto1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bto5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bto6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bto4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bto8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bto9, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bto7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto1MouseClicked

        cliqueUsuario(bto1);


    }//GEN-LAST:event_bto1MouseClicked

    private void bto2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto2MousePressed

        cliqueUsuario(bto2);


    }//GEN-LAST:event_bto2MousePressed

    private void btoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btoIniciarActionPerformed

        // Controla que a rodada está em execução
        rodadaIniciada(true);
        
        rodada++;
        jLabel1.setText("RODADA: " + rodada);
        player = -1;
        sequenciaPlayer.clear();

        GeradorSequencia gerador = new GeradorSequencia();

        // Prepara o array de botões
        JButton[] Botoes = {bto1, bto2, bto3, bto4, bto5, bto6, bto7, bto8, bto9};

        sequencia = gerador.geraSequencia(rodada, Botoes);
        clique = false;
        // Chama o método piscarBotoes com um callback para quando terminar
        PintarBotoes.piscarBotoes(sequencia, dificuldade, () -> {
            clique = true;
            JOptionPane.showMessageDialog(rootPane, "Agora é sua vez!");
        });

    }//GEN-LAST:event_btoIniciarActionPerformed

    private void bto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto3MouseClicked

        cliqueUsuario(bto3);


    }//GEN-LAST:event_bto3MouseClicked

    private void bto4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto4MouseClicked

        cliqueUsuario(bto4);

    }//GEN-LAST:event_bto4MouseClicked

    private void bto5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto5MouseClicked

        cliqueUsuario(bto5);


    }//GEN-LAST:event_bto5MouseClicked

    private void bto7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto7MouseClicked

        cliqueUsuario(bto7);


    }//GEN-LAST:event_bto7MouseClicked

    private void bto8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto8MouseClicked

        cliqueUsuario(bto8);


    }//GEN-LAST:event_bto8MouseClicked

    private void bto9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto9MouseClicked

        cliqueUsuario(bto9);


    }//GEN-LAST:event_bto9MouseClicked

    private void bto6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bto6MouseClicked
        // Prepara o array de botões

        cliqueUsuario(bto6);


    }//GEN-LAST:event_bto6MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

        switch (jComboBox1.getSelectedItem().toString()) {
            case "Fácil":
                dificuldade = 300;
                break;
            case "Médio":
                dificuldade = 200;
                break;
            case "Díficil":
                dificuldade = 100;
                break;
            default:
                break;

        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
    //Implemente o restante do código para controle de execução da rodada
    private void rodadaIniciada(boolean estado) {
        btoIniciar.setEnabled(!estado);
        habilitarBotoes(estado);

    }

    public void cliqueUsuario(JButton btn) {

        if (clique) {

            sequenciaPlayer.add(btn);
            botao.add(btn);

            PintarBotoes.piscarBotoes(botao, 100, () -> {
                clique = true;

                if (sequencia.get(player) != sequenciaPlayer.get(player)) {
                    rodadaIniciada(false);
                    rodada = 0;
                    JOptionPane.showMessageDialog(rootPane, " Game Over ");
                    salvarLista();
                    pontuacao = 0;

                } else if (sequenciaPlayer.size() == sequencia.size()) {
                    rodadaIniciada(false);
                    pontuacao += 1000;
                    jLabel2.setText("PONTUAÇÃO: " + pontuacao);
                }
                botao.clear();
            });
            player++;

        }
    }

    public void habilitarBotoes(boolean estado) {
        bto1.setEnabled(estado);
        bto2.setEnabled(estado);
        bto3.setEnabled(estado);
        bto4.setEnabled(estado);
        bto5.setEnabled(estado);
        bto6.setEnabled(estado);
        bto7.setEnabled(estado);
        bto8.setEnabled(estado);
        bto9.setEnabled(estado);
    }

    
    

    public void salvarLista() {
        String pontos = jTextField1.getText() + ": " + pontuacao;
        listModel.addElement(pontos);
        jList1.setModel(listModel);
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bto1;
    private javax.swing.JButton bto2;
    private javax.swing.JButton bto3;
    private javax.swing.JButton bto4;
    private javax.swing.JButton bto5;
    private javax.swing.JButton bto6;
    private javax.swing.JButton bto7;
    private javax.swing.JButton bto8;
    private javax.swing.JButton bto9;
    private javax.swing.JButton btoIniciar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
